pipeline:
  docker:
    image: plugins/docker
    repo: iteam1337/izone
    username: ${DOCKER_HUB_USER}
    password: ${DOCKER_HUB_PASS}
    email: ${DOCKER_HUB_EMAIL}
    tags: dotnet-core
  rancher:
    image: peloton/drone-rancher
    url: http://rancher.iteam.life:8080
    access_key: ${RANCHER_ACCESS_KEY}
    secret_key: ${RANCHER_SECRET_KEY}
    service: Izone/izone-rest
    docker_image: iteam1337/izone:dotnet-core
    confirm: true
    timeout: 120
