izone-core-api-mssql:
  image: microsoft/mssql-server-linux
  environment:
   - 'ACCEPT_EULA=Y'
   - 'SA_PASSWORD=ved-enozi'
  ports:
   - '1433:1433'

izone-core-api-rest:
  build: .
  environment:
   - 'DB__CONNECTIONSTRING=Data Source=sql; Database=izone-dev; User ID=sa; Password=ved-enozi;'
  links:
   - 'izone-core-api-mssql:sql'
  ports:
   - '3001:3000'

izone-core-migrations:
  build: .
  command: 'bash -c "cd /opt/src/Izone.DB.Migrations && dotnet ef database update && sleep 3600"'
  environment:
   - 'DB__CONNECTIONSTRING=Data Source=sql; Database=izone-dev; User ID=sa; Password=ved-enozi;'
  links:
   - 'izone-core-api-mssql:sql'
  ports:
   - '3000:3000'

